### ISSUE TITLE
Create database tables

### ISSUE THREAD

**Issue by chrsmendes** [bos21001/familiasm-api#11]
- [x] Create Laravel migrations for the tables: finances, finance_historys, groups, group_users
- [x] Run migrations to create tables in the database

**Comment by bos21001** [comment]
https://github.com/bos21001/familiasm-api/issues/7#issuecomment-1454996334

It was done in the #7 issue comment above

**Comment by bos21001** [comment]
Migrations created at commit 7bb550c
