### ISSUE TITLE
Add finance transactions (CRUD)

### ISSUE THREAD

**Issue by chrsmendes** [bos21001/familiasm-api#14]
- [x] Create routes and controllers to add, update, delete, and list finance transactions
- [x] Add appropriate validation and authorization to each route
> List or get finance transactions and all other CRUD has to be limited to the user which is requesting only. 
> i.e User 1 must NEVER see User 2 finances
- [x] Test finance transaction CRUD endpoints
- [x] #9 

Ref: #8

**Comment by bos21001** [comment]
#8 :

This issue's history covers the development of finance-related features in the application. It includes the creation of finance containers, migrations, setting up Eloquent relationships, making columns nullable, and changing the description column to long text. The issue also covers the implementation of finance transaction creation logic and improvements to the CreateFinance API endpoint response and documentation.

Additional enhancements involve setting up CRUD endpoints for finances, updating email verification requirements, and associating users with finances. The GetAllUserFinances endpoint was refactored to GetAllActualUserFinances to display only the logged-in user's finances. The FindFinanceById endpoint was updated to filter by user_id and restrict finance updates and deletions to their respective owners.

More information can be found at #8.
